### ISSUE TITLE
add -f number : use given frontend

### ISSUE THREAD

**Issue by montbell** [trollcop/recskapa#1]
Hello, could you add -f number : use given frontend (default 0)? This is because there are frontend0 and frontend1 under the /dev/dvb/adapter0 directory, and only frontend1 supports DVB-S2. Additionally, could you support an L.O. frequency of 11300 MHz?

**Comment by trollcop** [comment]
Hi, what card is this under? I thought `-a` or `--adapter` already supports selecting adapter. Are there cards with multiple frontends that work like this?

Anyway, it should be trivial to add, no problem. however `-f` is taken, so it will likely be `-n`. 

What skapa antenna uses LO of 10300? It's currently hardcoded, but I guess it could also be an option.

**Comment by trollcop** [comment]
Anyway, i added the above 2 options, please feel free to grab the code and test. I don't have any card where there are different frontends per adapter.

**Comment by montbell** [comment]
Thank you very much. I am using the TBS5520SE, which supports multiple standards, including DVB-S2X/S2/S/T2/T/C2/C/ISDB-T. Previously, I used `dvbv5-zap` and `szap-s2`, both of which support `-a` and `-f`. When using `recskapa`, it defaults to `frontend0`, causing failures, and I cannot select `frontend1`. 
﻿
Japan LNBs typically have an LO frequency of 11200 MHz, but I think it would be ideal if LO 11300 MHz could also be supported. Of course, Japan LNBs operate at voltages of 11V/15V. If LO 11300 MHz is supported, the voltage might differ as well, since LO 11300 MHz typically operates at 13V/18V. 
﻿
My requests are:  
1. To support selecting `frontend1`, similar to `-f number : use given frontend (default 0)`.  
2. (Optional) To support LO 11300 MHz."
Your help will be much appreciated.

**Comment by trollcop** [comment]
yep, already added both options
-n number = select frontend, default 0
-o 11300 = choose LO of 10300 MHz. Default is 11200 for skapa brand antennas.

**Comment by montbell** [comment]
Thank you very much. My device is now working properly. The `-n number = select frontend, default 0` option works perfectly. However, the `-o 11300` option doesn’t seem to take effect. When I use the `-o 11300` command, it still uses 11200, but I can adjust the frequency without affecting functionality. I must say that among the many software tools I’ve used, `recskapa` provides the most perfect support for 'TONE'. Using it, I was able to fully access both H/V polarizations on JCSAT3A/JCSAT4B.

**Comment by trollcop** [comment]
let me see this afternoon why LO might not be working.
i didn't test.

**Comment by trollcop** [comment]
> Thank you very much. My device is now working properly. The `-n number = select frontend, default 0` option works perfectly. However, the `-o 11300` option doesn’t seem to take effect. When I use the `-o 11300` command, it still uses 11200, but I can adjust the frequency without affecting functionality. 

oops, i fixed the LO stuff. Upper bound should have been higher than 10600, or else it never accepts 11300 as valid input. Anyway, fixed and commited - please test - should be OK to use `-o` option from now on.

> I must say that among the many software tools I’ve used, `recskapa` provides the most perfect support for 'TONE'. Using it, I was able to fully access both H/V polarizations on JCSAT3A/JCSAT4B.

Yeah, this was one of the reasons I used it. Other software makes it too annoying/complicated to do LNB switching for skapa.

**Comment by montbell** [comment]
I tested recompiling in the afternoon, and when using `-o 11300`, it indeed displayed "using LO of 11300MHz," but in reality, it was still using 11200MHz.

```bash
recskapa -a 0 -n 1 -b -o 11300 -l JCSAT4B -p H -f 12733 120 12733.ts
using device: /dev/dvb/adapter0
using frontend: 1
using B1...
using LO of 11300MHz
All tuning info provided, not using channel name
pid = 2301
device = /dev/dvb/adapter0/frontend1
Using DVB card "TurboSight TBS 5520SE DVB-S/S2/S2X"
Tuning to 1533.000 MHz
FE_SET_TONE failed: Connection timed out
polling.....
Cannot lock to the signal on the given channel
```

```bash
recskapa -a 0 -n 1 -b -o 11300 -l JCSAT4B -p H -f 12633 120 12733.ts
using device: /dev/dvb/adapter0
using frontend: 1
using B1...
using LO of 11300MHz
All tuning info provided, not using channel name
pid = 2879
device = /dev/dvb/adapter0/frontend1
Using DVB card "TurboSight TBS 5520SE DVB-S/S2/S2X"
Tuning to 1433.000 MHz
polling..ok
RF Level: -37.7 dBm SNR: 9.0 dB
Recording...
Recorded 120sec
Universal LNB
```

I believe the current version of `recskapa` is nearly perfect, as it works normally as long as the frequency is adjusted appropriately based on the LNB in use. I also tested using the command `recskapa -c /path/to/channel.conf -a 0 -n 1 -b -s <channel> - -` and confirmed that modifying the `skapa.conf` list works flawlessly.

**Comment by montbell** [comment]
I tested recompiling in the afternoon, and when using `-o 11300`, it indeed displayed "using LO of 11300MHz," but in reality, it was still using 11200MHz.

```bash
recskapa -a 0 -n 1 -b -o 11300 -l JCSAT4B -p H -f 12733 120 12733.ts
using device: /dev/dvb/adapter0
using frontend: 1
using B1...
using LO of 11300MHz
All tuning info provided, not using channel name
pid = 2301
device = /dev/dvb/adapter0/frontend1
Using DVB card "TurboSight TBS 5520SE DVB-S/S2/S2X"
Tuning to 1533.000 MHz
FE_SET_TONE failed: Connection timed out
polling.....
Cannot lock to the signal on the given channel
```

```bash
recskapa -a 0 -n 1 -b -o 11300 -l JCSAT4B -p H -f 12633 120 12733.ts
using device: /dev/dvb/adapter0
using frontend: 1
using B1...
using LO of 11300MHz
All tuning info provided, not using channel name
pid = 2879
device = /dev/dvb/adapter0/frontend1
Using DVB card "TurboSight TBS 5520SE DVB-S/S2/S2X"
Tuning to 1433.000 MHz
polling..ok
RF Level: -37.7 dBm SNR: 9.0 dB
Recording...
Recorded 120sec
```

I believe the current version of `recskapa` is nearly perfect, as it works normally as long as the frequency is adjusted appropriately based on the LNB in use. I also tested using the command `recskapa -c /path/to/channel.conf -a 0 -n 1 -b -s <channel> - -` and confirmed that modifying the `skapa.conf` list works flawlessly.

**Comment by montbell** [comment]
My issue has been resolved. If further modifications or tests are needed, I’d be happy to assist. Thank you very much!

**Comment by trollcop** [comment]
> I tested recompiling in the afternoon, and when using -o 11300, it indeed displayed "using LO of 11300MHz," but in reality, it was still using 11200MHz.

OK, sorry, I missed one final place where the frequency was being set. Please rebuild the code again.
Now it has been really fixed. `-o 11300` should work.

**Comment by montbell** [comment]
I think it's time to close this issue. I have updated to the latest code and tested it; **recskapa** now perfectly supports the `-n` and `-o` options.  
Here are the test results:  

```bash
recskapa -a 0 -n 1 -b -o 11300 -l JCSAT4B -p H -f 12733 120 12733.ts
using device: /dev/dvb/adapter0
using frontend: 1
using B1...
using LO of 11300MHz
All tuning info provided, not using channel name
pid = 1664
device = /dev/dvb/adapter0/frontend1
Using DVB card "TurboSight TBS 5520SE DVB-S/S2/S2X"
Tuning to 1433.000 MHz
polling..ok
RF Level: -37.7 dBm SNR: 8.8 dB
Recording...
Recorded 120sec
```

```bash
recskapa -c /usr/local/etc/skapa.conf -a 0 -n 1 -o 11300 -b -s CH640 120 640.ts
using device: /dev/dvb/adapter0
using frontend: 1
using LO of 11300MHz
using B1...
enable TS NULL strip
pid = 2081
Parsed channel CH640: 12733 H MHz, SR:23303000, 128E (DVB-S2)
device = /dev/dvb/adapter0/frontend1
Using DVB card "TurboSight TBS 5520SE DVB-S/S2/S2X"
Tuning to 1433.000 MHz
polling..ok
RF Level: -43.7 dBm SNR: 11.0 dB
Recording...
Recorded 120sec
```

Yes, everything is working perfectly. Whether it's JCSAT4B/JCSAT3A or H/V switching, everything works flawlessly. **recskapa** has brought me great convenience. I sincerely thank you for the time and effort you have put into this project. All issues have been resolved perfectly.
